### ISSUE TITLE
About enums in models

### ISSUE THREAD

**Issue by tcione** [vasconsaurus/produce_in_season#2]
I think there are two places we could benefit from using [`enums`](https://api.rubyonrails.org/v5.2.4.4/classes/ActiveRecord/Enum.html) instead of inclusion validation:

1. In https://github.com/vasconsaurus/produce_in_season/blob/main/app/models/produce_item.rb#L7-L8
```rb
  validates :category, presence: true,  inclusion: { in: %w[fruta legume verdura] }
```
could be
```rb
  CATEGORIES = %w[fruta legume verdura].freeze
  enum category: CATEGORIES.index_by(&:to_sym)
```

2. In https://github.com/vasconsaurus/produce_in_season/blob/main/app/models/item_season.rb
We could add
```rb
  COUNTRIES = %w[BR].freeze
  enum country_code: COUNTRIES.index_by(&:to_sym)
```

The cool thing about enums is that it adds:

a. Inclusion validations out of the box
b. Convenience methods. E.g, `produce_item.fruta?`

We could even go further and add enums [directly to Postgres](https://blog.saeloun.com/2022/01/12/rails-7-adds-custom-enum-support-in-postgresql.html). However I think it's over-engineering at this moment, since we'll be committing to a strict set of values from the get go, which might be undesirable in the future.

On a sidenote. I think we should be naming everything that's internal using English. Hence we should be naming categories in English (`fruit`, `vegetable`, `green`). WDYT[1]?

Please, let me know what do you think about both things (using enums and internal stuff in English) :D

**Comment by vasconsaurus** [comment]
when you write: `COUNTRIES.index_by(&:to_sym)` does it mean `COUNTRIES = {BR: "BR"}`? Is that so we can keep the column type as string?

about renaming the categories, completely agree

**Comment by tcione** [comment]
> when you write: `COUNTRIES.index_by(&:to_sym)` does it mean `COUNTRIES = {BR: "BR"}`? Is that so we can keep the column type as string?

Exactly. Otherwise rails transforms those into integers, which is hard to read in the database.
